services:

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootqwe123
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'

  api1:
    build: .
    hostname: api1
    expose:
      - "8081"
    environment:
      DB_USER: root
      DB_PASSWORD: rootqwe123
      DB_NAME: testdb
      DB_HOST: db
      INIT_SCHEMA: "true"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  api2:
    build: .
    hostname: api2
    expose:
      - "8081"
    environment:
      DB_USER: root
      DB_PASSWORD: rootqwe123
      DB_NAME: testdb
      DB_HOST: db
    depends_on:
      - db
      - api1
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  nginx:
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

volumes:
  pgdata:
